---
- hosts: masters
  become: true
  become_user: root
  gather_facts: yes
  connection: ssh
  tasks:
    - name: Mannually pull kube config images
      shell: kubeadm config images pull

    - name: Initialise the cluster # Ignore preflight-errors
      command: kubeadm init --pod-network-cidr=192.168.0.0/16 --kubernetes-version 1.23.0 --ignore-preflight-errors=ALL
      args:
        chdir: $HOME
        creates: cluster_initialized.txt
      run_once: true
      become_user: root
      become_method: sudo

    - pause: seconds=45

    - name: Create .kube directory
      become: true
      become_user: cloud_user
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: Copy admin.conf to User's kube config
      become_user: root
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/cloud_user/.kube/config
        remote_src: yes
        owner: cloud_user

    # - name: Setup kubeconfig for cloud_user user
    #     command: "{{ item }}"
    #     with_items:
    #     - mkdir -p $HOME/.kube
    #     - cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    #     - chown $(id -u):$(id -g) $HOME/.kube/config
    - name: Install Calico as Pod network
      become: false
      become_user: cloud_user
      shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
      args:
        chdir: $HOME
