---
- hosts: "masters, workers"
  become: true
  gather_facts: False

  vars_prompt:
    - name: "kube_user"
      prompt: "Mention non-root user to use Kubernetes cluster"
      private: no

  tasks:
    - name: Creating the user {{ kube_user }}.
      user:
        name: "{{ kube_user }}"
        createhome: yes
        shell: /bin/bash
        append: yes
        state: present

    - name: Create a dedicated sudo entry file for the user.
      file:
        path: "/etc/sudoers.d/{{ kube_user }}"
        state: touch
        mode: "0600"

    - name: "Setting up sudo password for user {{ kube_user }}."
      lineinfile:
        dest: "/etc/sudoers.d/{{ kube_user }}"
        line: "{{ kube_user }} ALL=(ALL) NOPASSWD: ALL"
        validate: "visudo -cf %s"

    - name: Set authorized key for user copying it from current "{{ kube_user }}" user.
      authorized_key:
        user: "{{ kube_user }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub')}}"

    - name: Print the created user.
      shell: id "{{ kube_user }}"
      register: new_user_created

    - debug:
      msg: "{{ new_user_created.stdout_lines[0] }}"
