---
- hosts: masters
  become: true
  become_user: root
  gather_facts: yes
  connection: ssh
  tasks:
    - name: Get join command
      shell: kubeadm token create --print-join-command
      register: join_command

    # - name: Copy join command to local file
    #   local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
    - name: Set join command
      set_fact:
        join_command: "{{ join_command.stdout_lines[0] }}"

- hosts: workers
  become: yes
  tasks:
    # # - name: Copy the join command to server location
    # #   copy: src=join-command dest=/tmp/join-command.sh mode=0777

    # - name: Join the node to cluster
    #   command: sh /tmp/join-command.sh
    #   become_user: root
    #   become_method: sudo
    #   register: joined_or_not

    # - debug:
    #     msg: "{{ joined_or_not.stdout }}"
    - name: join cluster
      shell: "{{ hostvars['master'].join_command }} --ignore-preflight-errors=ALL >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
