---
- name: Install Docker and Docker Compose on CentOS
  hosts: all
  become: true
  gather_facts: False

  tasks:
    - name: Remove docker if installed on CentOS
      yum:
        name:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
        state: absent
      run_once: true

    - name: Install required packages
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present
      when: ("ansible_facts['os_family'] == 'RedHat'") or (ansible_facts['distribution'] == "CentOS")
      run_once: true

    - name: Add docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
      run_once: true

    - name: Install Docker
      yum:
        name: ["docker-ce", "docker-ce-cli", "containerd.io"]
        state: present
      run_once: true

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes
      run_once: true

    - name: Check if Docker Compose is installed
      command: docker-compose --version
      register: docker_compose_check
      ignore_errors: yes

    - name: Download and install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.21.2/docker-compose-Linux-x86_64
        dest: /usr/bin/docker-compose
        mode: 0755
      when:
        - docker_compose_check.msg is defined
        - docker_compose_check.msg.find('No such file or directory') != -1
      run_once: true
